spotify_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: spotify
      password: spotify
      port: 5432
      dbname: spotify_analytics
      schema: analytics
      threads: 4
